
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class bill_record extends javax.swing.JFrame {
    Connection con=null;    
    ResultSet rs=null;
    PreparedStatement pst=null;

    /**
     * Creates new form bill_record
     */
    public bill_record() {
        initComponents();
        con= connect.ConnectDB();
        Get_Data();
        setLocationRelativeTo(null);
    }
        private void Get_Data(){
         try{
             
                String sql="Select bill_no as 'Bill No.',registration.pid as 'Patient ID',registration.name as 'Patient Name',registration.gender as 'Gender',registration.bgrp as 'Blood Group',admit.disease,admit.adate as 'Admit Date',room.rno as 'Room No',doctor.did as 'Doctor ID',doctor.name as 'Doctor Name',discharge.ddate as 'Discharge Date',billing.toal_room as 'Room Charges',service.scharge as 'Service Charges',billing.bdate as 'Billing Date',paymode as 'Payement Mode',paydetails as 'Payment Mode Details',no_days as 'No. Of Days' from service,room,doctor,registration,admit,discharge,billing where room.rno=admit.room_no and doctor.did=admit.did and registration.pid=admit.pid and admit.pid= discharge.admit_id and billing.discharge_id=discharge.admit_id order by bdate"; 
                pst=con.prepareStatement(sql);
                rs= pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));

         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
       try{
            con=connect.ConnectDB();
            int row= jTable1.getSelectedRow();
            this.hide();
            biling frm = new biling();
            frm.setVisible(true);
            String add= jTable1.getModel().getValueAt(row, 0).toString();
            frm.bill.setText(add);
             String add3= jTable1.getModel().getValueAt(row, 1).toString();
            frm.pid.setText(add3);
              String add4= jTable1.getModel().getValueAt(row, 2).toString();
            frm.pname.setText(add4);
              String add5= jTable1.getModel().getValueAt(row, 3).toString();
            frm.gender.setSelectedItem(add5);
              String add6= jTable1.getModel().getValueAt(row, 4).toString();
            frm.bgrp.setSelectedItem(add6);
              String add7= jTable1.getModel().getValueAt(row, 5).toString();
            frm.disease.setText(add7);
              String add8= jTable1.getModel().getValueAt(row, 6).toString();
            frm.adate.setText(add8);
              String add9= jTable1.getModel().getValueAt(row, 7).toString();
            frm.rno.setText(add9);
              String add10= jTable1.getModel().getValueAt(row, 8).toString();
            frm.did.setText(add10);
              String add11= jTable1.getModel().getValueAt(row, 9).toString();
            frm.dname.setText(add11);
              String add12= jTable1.getModel().getValueAt(row, 10).toString();
            frm.ddate.setText(add12);
              String add13= jTable1.getModel().getValueAt(row, 11).toString();
            frm.rcharge.setText(add13);
              String add14= jTable1.getModel().getValueAt(row, 12).toString();
            frm.scharge.setText(add14);
              String add15= jTable1.getModel().getValueAt(row, 13).toString();
            frm.bdate.setText(add15);
            String add16= jTable1.getModel().getValueAt(row, 14).toString();
            frm.payment.setSelectedItem(add16);
            String add17= jTable1.getModel().getValueAt(row, 15).toString();
            frm.pdetails.setText(add17);
            String add19= jTable1.getModel().getValueAt(row, 16).toString();
             frm.days.setText(add19);
            frm.pid.setText(add3);
            frm.update.setEnabled(true);
            frm.delete.setEnabled(true);
            frm.save.setEnabled(false);
          }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill_record().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
